# Generated by Django 2.2.6 on 2019-10-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='RatingShool',
            field=models.FloatField(),
        ),
    ]
