# Generated by Django 2.2.6 on 2020-01-17 02:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20191101_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(default=None, max_length=30)),
                ('Email', models.EmailField(default=None, max_length=254, unique=True)),
                ('Rut', models.CharField(default=None, max_length=14)),
                ('Region', models.CharField(default=None, max_length=50)),
                ('Comuna', models.CharField(default=None, max_length=50)),
                ('Metodo', models.CharField(default=None, max_length=16)),
                ('Msg', models.TextField(default=None, max_length=1000)),
                ('Newsletter', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='state_province',
            old_name='Name',
            new_name='NameSP',
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='Rating',
        ),
        migrations.RemoveField(
            model_name='school',
            name='RatingShool',
        ),
        migrations.AddField(
            model_name='ratings',
            name='Score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Evaluacion de la escuela'),
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='Schools',
        ),
        migrations.AddField(
            model_name='ratings',
            name='Schools',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalog.School'),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='school',
            name='ImageMD',
            field=models.ImageField(upload_to='static/img/modal'),
        ),
        migrations.AlterField(
            model_name='school',
            name='Review',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='school',
            name='State_Province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.state_province'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
