# Generated by Django 2.2.6 on 2019-11-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20191101_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='Review',
            field=models.TextField(max_length=1500),
        ),
    ]
