# Generated by Django 2.2.6 on 2019-11-01 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20191101_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='State_Province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.state_province'),
        ),
    ]
