# Generated by Django 2.2.6 on 2019-11-01 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20191101_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state_province',
            old_name='Name',
            new_name='NameSP',
        ),
    ]
