# Generated by Django 2.2.6 on 2019-11-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20191101_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='User',
        ),
        migrations.AddField(
            model_name='ratings',
            name='User',
            field=models.ManyToManyField(to='catalog.User'),
        ),
    ]
