# Generated by Django 2.2.6 on 2019-11-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20191105_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='RatingShool',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
