# Generated by Django 2.2.6 on 2019-11-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20191106_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='ShortReview',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
