# Generated by Django 2.2.6 on 2019-11-06 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_remove_school_shortreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='Review',
            field=models.TextField(max_length=1500),
        ),
    ]
