# Generated by Django 2.2.6 on 2019-11-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20191106_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='ShortReview',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='Review',
            field=models.TextField(max_length=2000),
        ),
    ]
