# Generated by Django 2.2.6 on 2019-11-09 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20191106_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='RatingShool',
            new_name='Score',
        ),
    ]
