# Generated by Django 2.2.6 on 2019-11-09 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20191109_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='ShortReview',
        ),
    ]
