# Generated by Django 2.2.6 on 2019-11-09 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20191109_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='Schools',
        ),
        migrations.AddField(
            model_name='ratings',
            name='Schools',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalog.School'),
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='User',
        ),
        migrations.AddField(
            model_name='ratings',
            name='User',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalog.User'),
            preserve_default=False,
        ),
    ]
