# Generated by Django 2.2.6 on 2019-11-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20191112_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='Score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
