# Generated by Django 2.2.6 on 2019-11-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20191112_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='Score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
