# Generated by Django 2.2.6 on 2019-11-16 20:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20191112_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoModel',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
