# Generated by Django 2.2.6 on 2019-11-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_contactomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactomodel',
            name='Email',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
    ]
