# Generated by Django 2.2.6 on 2019-11-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_contactomodel_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactomodel',
            name='Comuna',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='contactomodel',
            name='Region',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
