# Generated by Django 2.2.6 on 2019-11-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_auto_20191116_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactomodel',
            name='Metodo',
            field=models.CharField(default=None, max_length=16),
        ),
    ]
