# Generated by Django 2.2.6 on 2019-11-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_contactomodel_metodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactomodel',
            name='Msg',
            field=models.TextField(default=None, max_length=1000),
        ),
    ]
