# Generated by Django 2.2.6 on 2019-11-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_contactomodel_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactomodel',
            name='Newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
