# Generated by Django 2.2.6 on 2019-11-17 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_contactomodel_newsletter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactoModel',
            new_name='ContactModel',
        ),
    ]
