# Generated by Django 2.2.6 on 2019-11-17 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_auto_20191117_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='Nombre',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
