# Generated by Django 2.2.6 on 2019-11-17 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_contactmodel_nombre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
