# Generated by Django 2.2.6 on 2019-11-18 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_auto_20191117_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
