# Generated by Django 2.2.6 on 2019-11-18 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_auto_20191117_2102'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
