# Generated by Django 2.2.6 on 2019-11-24 20:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='Score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
