# Generated by Django 2.2.6 on 2019-11-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_auto_20191124_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='Score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
