# Generated by Django 2.2.6 on 2019-11-24 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_auto_20191124_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='Score',
        ),
    ]
